// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mntcpyczditjzeemqcmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1udGNweWN6ZGl0anplZW1xY210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjk0ODcsImV4cCI6MjA2Mzk0NTQ4N30.WFX7yjtNYe1eKglxAmJH22kMLdw2OXz_SSrLTZG_bjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);